quarkus:
  datasource:
    db-kind: mysql 
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://localhost:3306/hotel_simple_app?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      driver: com.mysql.cj.jdbc.Driver
      
    hibernate-orm:
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        timezone: UTC
    
  # Flyway minimal config properties
  flyway:
    migrate-at-start: true

    # Flyway optional config properties
    # Drop all objects into the DB (only for DEV purpose)
    clean-at-start: true
    baseline-on-migrate: true
    table: flyway_quarkus_history
    locations: db/migration
    # baseline-version: 1.0.0
    # baseline-description: Initial version
    # connect-retries: 10
    # schemas: TEST_SCHEMA
    # sql-migration-prefix: X
    # repeatable-sql-migration-prefix: K