CREATE TABLE guest(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	dateOfBirth DATE NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	phoneNumber VARCHAR(25)
);