CREATE TABLE guest(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	birth_date DATE NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	phone_number VARCHAR(25)
);

CREATE TABLE room(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	number INT NOT NULL UNIQUE
);